"""
The Treasure Chest — yer plunderable media library.

Loads from media_library.json (generated by scrape_yts.py).
You can also add manual entries to EXTRA_MEDIA below.
"""

import json
import os

_LIBRARY_JSON = os.path.join(os.path.dirname(os.path.abspath(__file__)), "media_library.json")


def _load_library():
    if os.path.exists(_LIBRARY_JSON):
        with open(_LIBRARY_JSON, "r") as f:
            return json.load(f)
    return []


# Auto-loaded from media_library.json (scraped catalog)
SCRAPED_MEDIA = _load_library()

# Add any manual entries here
EXTRA_MEDIA = [
    # {
    #     "id": "my-custom-movie",
    #     "title": "My Custom Movie",
    #     "year": 2024,
    #     "category": "movie",
    #     "description": "A movie I added manually.",
    #     "torrent_url": "magnet:?xt=urn:btih:HASH_HERE",
    #     "image_url": "",
    # },
]

MEDIA_LIBRARY = EXTRA_MEDIA + SCRAPED_MEDIA
